from setuptools import setup

setup(name='vcontact2',
      version='0.9.18',
      description='Viral Contig Automatic Clutering and Taxonomy',
      url='https://bitbucket.org/MAVERIClab/vcontact2',
      author='Benjamin Bolduc',
      long_description_markdown_filename='README.md',
      author_email='bolduc.10@osu.edu',
      license='GPLv3',
      packages=['vcontact2', 'vcontact2.exports', 'vcontact2.utilities'],
      package_data={'vcontact2': ['data/ViralRefSeq-prokaryotes-v88.faa.gz',
                                  'data/ViralRefSeq-prokaryotes-v88.protein2contig.csv',
                                  'data/ViralRefSeq-prokaryotes-v88.Merged-reference.csv',
                                  'data/ViralRefSeq-prokaryotes-v85.faa.gz',
                                  'data/ViralRefSeq-prokaryotes-v85.protein2contig.csv',
                                  'data/ViralRefSeq-prokaryotes-v85.ICTV-reference.csv',
                                  'data/ViralRefSeq-prokaryotes-v85.Merged-reference.csv',
                                  'data/ViralRefSeq-archaea-v85.faa.gz',
                                  'data/ViralRefSeq-archaea-v85.protein2contig.csv',
                                  'data/ViralRefSeq-archaea-v85.Merged-reference.csv',
                                  'data/ViralRefSeq-prokaryotes-v94.faa.gz',
                                  'data/ViralRefSeq-prokaryotes-v94.protein2contig.csv',
                                  'data/ViralRefSeq-prokaryotes-v94.Merged-reference.csv',
                                  'data/ViralRefSeq-archaea-v94.faa.gz',
                                  'data/ViralRefSeq-archaea-v94.protein2contig.csv',
                                  'data/ViralRefSeq-archaea-v94.Merged-reference.csv'
                                  'data/ViralRefSeq-prokaryotes-v97.faa.gz',
                                  'data/ViralRefSeq-prokaryotes-v97.protein2contig.csv',
                                  'data/ViralRefSeq-prokaryotes-v97.Merged-reference.csv',
                                  'data/ViralRefSeq-archaea-v97.faa.gz',
                                  'data/ViralRefSeq-archaea-v97.protein2contig.csv',
                                  'data/ViralRefSeq-archaea-v97.Merged-reference.csv',
                                  'data/ViralRefSeq-prokaryotes-v201.faa.gz',
                                  'data/ViralRefSeq-prokaryotes-v201.protein2contig.csv',
                                  'data/ViralRefSeq-prokaryotes-v201.Merged-reference.csv',
                                  'data/ViralRefSeq-archaea-v201.faa.gz',
                                  'data/ViralRefSeq-archaea-v201.protein2contig.csv',
                                  'data/ViralRefSeq-archaea-v201.Merged-reference.csv'
                                  ]},
      scripts=['bin/vcontact2', 'bin/vcontact2_gene2genome'],
      setup_requires=['setuptools-markdown'],
      install_requires=[
        'networkx>=2.2',
        'numpy>=1.15.4',
        'scipy>=1.2.0',
        'pandas>=0.25.0,<=0.25.3',
        'scikit-learn>=0.20.2',
        'biopython>=1.73',
        'tables>=3.4.0',
        'pyparsing>=2.4.6'
      ]
      )
